defaults:
    - default
    - data: kitti_360
    - _self_

name: "eval_lidar_occ"
model: "eval_kyn"
checkpoint: "checkpoints/kyn.pt"

log_every: 500
batch_size: 1
num_workers: 10

data:
    image_size: [192, 640]
    data_3d_bboxes: false
    data_segmentation: false
    data_fisheye: false
    data_stereo: false
    data_fc: 1
    is_preprocessed: false
    # directory to put test images and poses
    data_path: "./KITTI-360"
    pose_path: "./KITTI-360/data_poses"

model_conf:
    arch: "KYN"
    use_code: true
    prediction_mode: default
    code:
        num_freqs: 6
        freq_factor: 1.5
        include_input: true
    encoder:
        type: "vl_encoder"
        use_vision_model: true
        use_vlseg_model: true
        freeze_vision_model: false
        freeze_vlseg_model: true
        resnet_layers: 50
        num_ch_dec: [32,32,64,128,256]
        vision_d_out: 64
        # language settings
        ov_label_path: "datasets/ov_labels/outdoor_labels.txt"
        lseg_model_path: "checkpoints/demo_e200.ckpt"
        fuse_type: "concat_reg"
        return_only_feat: false
    mlp_coarse:
        type : "vl_modulation_attention"
        d_hidden : 128
        attn_head: 4
        attn_kv_ch: 32
        lin_attn_type: "img_softmax_q"
        use_q_residual: true
        use_valid_pts_mask: true
        n_blocks : 4
        skip_layers: [2]
    mlp_fine:
        type : "empty"
        n_blocks : 1
        d_hidden : 128

    z_near: 3
    z_far: 80

    # scene-level evaluation settings
    x_range: [-4, 4]
    y_range: [0, .75] 
    z_range: [50, 4]
    ppm:  10
    ppm_y: 4
    y_res: 1
    gt_aggregate_timesteps: 300
    cut_far_invisible_area: true
    save_gt_occ_map_path: ""
    read_gt_occ_path: "./KITTI-360/GT_Occ"
    # object-level evaluation settings
    is_eval_object: true
    read_gt_obj_path: "./KITTI-360/Object_Label"
    obj_z_expand: 2
    obj_x_expand: 0.5


    ray_batch_size: 256
    code_mode: z
    inv_z: true
    learn_empty: false
    n_frames_encoder: 1
    n_frames_render: 1
    sample_color: true

renderer:
    n_coarse : 64
    n_fine : 0
    n_fine_depth : 0
    depth_std : 1.0
    sched : []
    white_bkgd : false
    lindisp: true
    hard_alpha_cap: true
